### ISSUE TITLE
Precompile source code and host HEX file

### ISSUE THREAD

**Issue by kk6axq** [BYU-MAGICC/ROSflight_old#1]
Is it possible for you to post the compiled hex file of the binary Naze firmware to the repo that way it will save other people time in compiling and setup of the toolchain?

**Comment by superjax** [comment]
I would be willing to send it to you, but I don't have a great place to host it.  Could I PM it to you?

**Comment by kk6axq** [comment]
Feel free to PM it to me. Just a thought, it is possible to host the file in this or some other repo...

**Comment by superjax** [comment]
I just created a release for the last definitely working version of our code, and I put the binary up with it.  (We've been adding some extra sensors in preparation for fixed wing flight).  Stay tuned for the fixed wing version.
